### Python Datascience 

This week we are going to use jupyter lab and jupyter notebooks to run our code 

- previously we used 
    - `spyder` on our local machines
    - `atom` on our local machines to remotely edit files on the server (though the `ftp-remote-edit package`) and run them through the terminal in atom that we connected to the cgat cluster using `ssh`
    
This week we are using `jupyter lab` and `jupyter notebooks` because we are doing some 'data science'.
This invloves looking at your files more and plotting things and its handy to be able to look at your output in the same document that your have your code. 

Jupyter notebooks allow you to:
- write text in 'markdown' format to annotate your code
- interactively write code and see what it outputs 
- display the output right where you've run it
- run command line statements 



All of the above, allow you to create a 'lab book' style document or report.


`.ipynb` files that can be easily converted to:
- a nice `.html` document or report thats easy to share and impress your colleagues
- a python script - sometimes handy if your trying out code but ultimately want a `.py` file to run 
- to do this you can click on `File/Export Notebook As` then choose `executable script` for `.py` file or `html` or `pdf` etc. 
    

### To run code in cells 

`Crl` + `Enter`

### Add Cells to run code in 
Click the '+' button above

### Good practise for Notebooks 

- At top of notebook run: 
    - date
    - the directory its running in 
    - your conda env 
    
We can use bash to get all of these - using the jupyter notebook and ipython magic `!`

In [64]:
!date
!pwd
! conda env list | grep '*'

Tue Feb  9 12:48:06 GMT 2021
/ifs/obds-training/jan21/paulm/python_datascience
obds_py3              *  /ifs/obds-training/jan21/paulm/conda/obds_conda/envs/obds_py3


### Numpy 

- Mathematical library 
- Fast mathmatical opertations on numeric datatypes 
- Allows N-dimensional tables - all must be same type (int64, float64 etc)
- Matrix Algebra
- Data structure = 'Arrays' (fast access to numeric data)

In [65]:

# import numpy library -> enable mathematical operations and create mutidimensional arrays
import numpy as np 

# create 2D matrix using np.array()  
x = np.array([[1,2,3],
              [4,5,6]], dtype=np.float64)
print('x')
print(x)


y = np.array([[7,8,9],
              [10,11,12]], dtype=np.float64)
print('y')
print(y)

x
[[1. 2. 3.]
 [4. 5. 6.]]
y
[[ 7.  8.  9.]
 [10. 11. 12.]]


#### Can do matrix algebra

In [66]:
# sum the elements of 2 matrices together
print('Output from x+y :')
print(x + y)
print()  # this just outputs an empty line to make the output look cleaner

print('Can also use np.add(x,y) function:')
print(np.add(x,y))

Output from x+y :
[[ 8. 10. 12.]
 [14. 16. 18.]]

Can also use np.add(x,y) function:
[[ 8. 10. 12.]
 [14. 16. 18.]]


#### Transpose (swap) rows and columns

In [67]:
# origional x
print('Origional x')
print(x)

print()

# transpose x using .T
print("Transposed x")
print(x.T)

Origional x
[[1. 2. 3.]
 [4. 5. 6.]]

Transposed x
[[1. 4.]
 [2. 5.]
 [3. 6.]]


#### Numpy slicing of arrays 

- arrayname[rows, columns] 
- remember python is 0 based (start at 0)
- start_positon : end_possition + 1  -> get first 4 elements -> [0:5]

In [68]:
z = [1,2,3,4,5,6,7,8,9]
z[0:4]

[1, 2, 3, 4]

In [69]:
# slicing array_name[cols, rows] ????????

# origional x
print('Origional x')
print(x)

print()

print ('x[:2] = rows from start to 2nd possition (row 0&1)')
print(x[:2])

print() 

print ('x[:, 1:3] = all rows, cols from start to 3rd possition (col 1-3)')
print(x[:,1:3])

print() 

print ('x[:2,1:3] = row 0 & 1 & col 1 - 2')
b = x[:2,1:3]
b

Origional x
[[1. 2. 3.]
 [4. 5. 6.]]

x[:2] = rows from start to 2nd possition (row 0&1)
[[1. 2. 3.]
 [4. 5. 6.]]

x[:, 1:3] = all rows, cols from start to 3rd possition (col 1-3)
[[2. 3.]
 [5. 6.]]

x[:2,1:3] = row 0 & 1 & col 1 - 2


array([[2., 3.],
       [5., 6.]])

## Pandas = dataframes in python 

- built on numpy arrays
- adds rows and column metadata & labels 

#### Dataframes 

- one datatype per column (e.g. str, int, float, list etc.)
- Can be created from any 2D python data structure
    - Dictionary of lists
    - Dictionary of tuples 
    - Dictionary of series
    - Dictionary of Dictionaries 
    - List of dictionaries

### Pandas Series

- 1D vector built on NumPy array
- Includes label vector - can index on this
- Slice like a list [start_possition : stop_possition +1]
- Can have a series of any python object (e.g. str, int, float, boolean, dict, list etc)
- Must be all the same object type

In [70]:
# import numpy
import numpy as np
# import pandas
import pandas as pd

#### Create series with index or without

In [71]:
# pandas creates default integer index​
s = pd.Series(['one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight'])
s

0      one
1      two
2    three
3     four
4     five
5      six
6    seven
7    eight
dtype: object

In [72]:
# pandas creates default integer index
# np.random.randn(5) = make array with 5 random numbers
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s

a   -0.703589
b    1.506506
c   -1.307341
d   -0.824590
e    0.917758
dtype: float64

#### Print attribute of series (e.g. index or name)

In [73]:
# index & name are attributes of Series class​
print(s.index)
print(s.name)  # no name currently

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
None


### Slicing series

In [74]:
# Slicing

print('Origional s:')
print(s, '\n') # print s then an empty line

print('s[:3] -> positions 0,1,2')

s[:3]        # list like slicing - pos 0-2

print(s[:3], '\n')

s['a']       # Index using labels

print("s['a'] -> value for pos 'a'")
print(s['a'], '\n')

s[[4, 3, 1]] # array-based indexing 

print('s[[4,3,1]] -> pos 4, 3, 2')
print(s[[4, 3, 1]], '\n')


Origional s:
a   -0.703589
b    1.506506
c   -1.307341
d   -0.824590
e    0.917758
dtype: float64 

s[:3] -> positions 0,1,2
a   -0.703589
b    1.506506
c   -1.307341
dtype: float64 

s['a'] -> value for pos 'a'
-0.7035889677989913 

s[[4,3,1]] -> pos 4, 3, 2
e    0.917758
d   -0.824590
b    1.506506
dtype: float64 



#### Element wide computation

In [75]:
s = pd.Series([1,2,3,4,5,6,7,8,9,10])

print('origional S')
print(s)
print()

s + s # element-wise addition
print('s + s')
print(s+s)
print()

s * 2 # element-wise multiplication
print('s * 2')
print(s*2)
print()

origional S
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

s + s
0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
8    18
9    20
dtype: int64

s * 2
0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
8    18
9    20
dtype: int64



#### Create Dataframes

From a dictionary of series (could also be a dict of lists etc)

In [76]:


# dictionary - col names are dict 'keys', values are all in a 'list'
dict_of_genes = {'genes': ['Actb','Per1', 'Gapdh', 'Gata1','Eno1'], 
                 'counts': [550, 45, 984, 600, 123],
                 'control': [True, False, True, False, False]}

# use df as short for dataframe

df = pd.DataFrame(dict_of_genes)
df

genes  counts  control
0   Actb     550     True
1   Per1      45    False
2  Gapdh     984     True
3  Gata1     600    False
4   Eno1     123    False

In [77]:
# Dataframe from dictionary of series
d = {'one': pd.Series([1., 2., 3.], 
                      index=['a', 'b', 'c']),
     'two': pd.Series([1., 2., 3., 4.],
                      index=['a', 'b', 'c', 'd'])}

print(d)

df = pd.DataFrame(d)
df

{'one': a    1.0
b    2.0
c    3.0
dtype: float64, 'two': a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64}


one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

#### Read and write Dataframes from and to files 

#### Get Attributes of a Dataframe

In [78]:
df.index   # row labels

Index(['a', 'b', 'c', 'd'], dtype='object')

In [79]:
df.columns # column labels

Index(['one', 'two'], dtype='object')

In [80]:
df.shape   # dataframe size

(4, 2)

#### Viewing dataframes

df.head()

df.tail()

#### Get Summary of Dataframe information
 
df.info()

df.describe()

#### REad and write dataframe to file

```
# Read and write to CSV
df = pd.read_csv('file.csv')
df.to_csv('output.csv')

# tsv
df = pd.read_csv('file.tsv', sep='\t‘, header=0) df = pd.read_table(file_path) # tab default

# Excel
df = pd.read_excel('file.xlsx', 'Sheet1', index_col=None, na_values=['NA'])
df.to_excel('outfile.xlsx',sheet_name='Sheet1')

# HDF5
df = pd.read_hdf('file.h5', 'df')
df.to_hdf('foo.h5', 'df')
```

#### Add columns

In [81]:
# Adding columns
df['three'] = df['one'] * df['two']
df['flag'] = df['one'] > 2

# Assign – (like dplyr mutate)
df = df.assign(four = df['one'] /df['two'])
df

one  two  three   flag  four
a  1.0  1.0    1.0  False   1.0
b  2.0  2.0    4.0  False   1.0
c  3.0  3.0    9.0   True   1.0
d  NaN  4.0    NaN  False   NaN

#### Delete Columns

In [82]:
df.drop('four',axis=1) # need to save this to a variable to take effect, or use inplace=True in parameters

one  two  three   flag
a  1.0  1.0    1.0  False
b  2.0  2.0    4.0  False
c  3.0  3.0    9.0   True
d  NaN  4.0    NaN  False

In [83]:
four = df.pop('four')
print(four)

a    1.0
b    1.0
c    1.0
d    NaN
Name: four, dtype: float64


#### Dataframe slicing, selecting and subsetting

In [84]:
# Select single column
df['one']

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [85]:
# Select multiple columns (list)
df[['two', 'one']] # any order

two  one
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  4.0  NaN

In [86]:
# Slice data frame [rows]
df[:3]

one  two  three   flag
a  1.0  1.0    1.0  False
b  2.0  2.0    4.0  False
c  3.0  3.0    9.0   True

In [87]:
# get row by label -> returns series 
df.loc['b',:]

one          2
two          2
three        4
flag     False
Name: b, dtype: object

In [88]:
# get row by label and then specific columns 
df.loc['c':, 'one':'three']


one  two  three
c  3.0  3.0    9.0
d  NaN  4.0    NaN

In [89]:
# get row by interger location 
df.iloc[2:]
df.iloc[1:3, 2:3]

three
b    4.0
c    9.0

#### Boolean Indexing -> returns a dataframe

In [90]:
# select rows on column values
df[df.one > 1]    # can also do df[df['one'] > 1]

one  two  three   flag
b  2.0  2.0    4.0  False
c  3.0  3.0    9.0   True

In [91]:
# select values on condition
df[df > 2]

one  two  three  flag
a  NaN  NaN    NaN   NaN
b  NaN  NaN    4.0   NaN
c  3.0  3.0    9.0   NaN
d  NaN  4.0    NaN   NaN

### Exercise1

1) Read in a idxstats table you have generated for one of your samples on the course and save to variable called `idxdf`

In [92]:
idxdf = pd.read_csv("/ifs/obds-training/jan21/exercises/rnaseq/room1/sam/ERR1755082.idxstats", sep = '\t', header = None)
idxdf

0          1        2        3
0    chr1  195471971  7505663   323256
1   chr10  130694993  4880751   248716
2   chr11  122082543  7452789   385535
3   chr12  120129022  3104950   145924
4   chr13  120421639  3222176   150791
5   chr14  124902244  3975495   191228
6   chr15  104043685  3796740   194000
7   chr16   98207768  2481586   122178
8   chr17   94987271  5794590   280652
9   chr18   90702639  2167389   103901
10  chr19   61431566  3573941   183566
11   chr2  182113224  6596073   320953
12   chr3  160039680  4062539   197868
13   chr4  156508116  5264332   262146
14   chr5  151834684  5440642   263428
15   chr6  149736546  4683974   223154
16   chr7  145441459  7687960   361209
17   chr8  129401213  4345076   212528
18   chr9  124595110  5147071   247008
19   chrM      16299  2421340    80238
20   chrX  171031299  3431992   151970
21   chrY   91744698   310467    15700
22      *          0        0  2305942

2) Assign column names to table -> see http://www.htslib.org/doc/samtools-idxstats.html

In [93]:
idxdf.columns = ["seq_name", "seq_length", "mapped_reads", "unmapped_reads"]
idxdf

seq_name  seq_length  mapped_reads  unmapped_reads
0      chr1   195471971       7505663          323256
1     chr10   130694993       4880751          248716
2     chr11   122082543       7452789          385535
3     chr12   120129022       3104950          145924
4     chr13   120421639       3222176          150791
5     chr14   124902244       3975495          191228
6     chr15   104043685       3796740          194000
7     chr16    98207768       2481586          122178
8     chr17    94987271       5794590          280652
9     chr18    90702639       2167389          103901
10    chr19    61431566       3573941          183566
11     chr2   182113224       6596073          320953
12     chr3   160039680       4062539          197868
13     chr4   156508116       5264332          262146
14     chr5   151834684       5440642          263428
15     chr6   149736546       4683974          223154
16     chr7   145441459       7687960          361209
17     chr8   129401213       4345076          212528
18     chr9   124595110       5147071          247008
19     chrM       16299       2421340           80238
20     chrX   171031299       3431992          151970
21     chrY    91744698        310467           15700
22        *           0             0         2305942

3)Apply the `describe()` and `info()` methods to the `idxdf` object

In [94]:
print(idxdf.describe())
print(idxdf.info())
print(idxdf.describe().info())
print(idxdf.info().describe())

         seq_length  mapped_reads  unmapped_reads
count  2.300000e+01  2.300000e+01    2.300000e+01
mean   1.185016e+08  4.232502e+06    3.031257e+05
std    4.911871e+07  2.051681e+06    4.457848e+05
min    0.000000e+00  0.000000e+00    1.570000e+04
25%    9.659752e+07  3.163563e+06    1.513805e+05
50%    1.245951e+08  4.062539e+06    2.125280e+05
75%    1.507856e+08  5.352487e+06    2.720400e+05
max    1.954720e+08  7.687960e+06    2.305942e+06
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   seq_name        23 non-null     object
 1   seq_length      23 non-null     int64 
 2   mapped_reads    23 non-null     int64 
 3   unmapped_reads  23 non-null     int64 
dtypes: int64(3), object(1)
memory usage: 864.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, count to max
Data columns (total 3 columns):
 #   Column          No

AttributeError: 'NoneType' object has no attribute 'describe'

4)Look at the `shape` and `index` attributes of `idxdf`

In [ ]:
shape_idxdf = idxdf.shape
print(shape_idxdf)
print(idxdf.index)


5) From `idxdf` select rows 6-12 and create a new variable called `idxdf2` 

In [ ]:
idxdf2 = idxdf[6:13]
idxdf2

6) From `idxdf` make a new dataframe `chr_mapped` consisting of columns 1&3 (chr & mapped). Save to a new file called `mapped_reads_per_chr.tsv` - make sure the output is tab seperated​


In [ ]:
seq_mapped = idxdf[['seq_name','mapped_reads']]
display(seq_mapped.to_csv('mapped_reads_per_chr.tsv', sep="\t", header= True, index = False))


In [ ]:
!ls

7) Create a new column for idxdf called `reads_per_base` by dividing number of `mapped reads` by `length` column

In [ ]:
idxdf['reads_per_base'] = idxdf['mapped_reads']/idxdf['seq_length']
print(idxdf)

8) Subset the rows that have `reads_per_base` values greater than 0.05

In [ ]:
readsperbase_over5 = idxdf[idxdf['reads_per_base'] > 0.05]
readsperbase_over5

9)Create a new column of length / 1 million to give a `length_Mbs` column (length in Megabases)

In [ ]:
idxdf['length_Mbs'] = idxdf['seq_length']/1000000
display(idxdf)

10) Subset the rows that have `reads_per_base` values greater than 0.05 and a chromosome length under 100 Mb

In [ ]:
subset1 = idxdf[ (idxdf['reads_per_base'] > 0.05) & (idxdf['length_Mbs'] < 100)]
subset1


11) Delete the `reads_per_base` column

In [ ]:
idxdf.drop('reads_per_base', axis = 1, inplace = True)
display(idxdf)

#### Sorting Dataframes 

```
# Sort by single column
df.sort_values(by=['col1'])

# Sort by multiple columns
df.sort_values(by=['col1', 'col2'])

# Descending order
df.sort_values(by='col1', ascending=False)

# NAs first
df.sort_values(by='col1', ascending=False, na_position='first')
```

#### Operations 
```
# Element-wise mathematical operations
df * 5
df **3

# Boolean logic
df1 & df2

# Numpy functions
np.log(df)

# Statistical summary
df.describe()

# statistical functions
df.mean() # per column
df.mean(axis=1) # per row

# Matrix algebra
df.T # transpose of matrix 
df.dot(df) # matrix multiplication

```

#### Apply Functions along an axis

```
# apply to entire dataframe
df.apply(np.sqrt)

# apply to cols
df.apply(np.sum, axis=0)


# apply to rows
df.apply(np.sum, axis=1)


```

#### Missing Data

```
# drop rows with nan
df.dropna(how='any')

# Replace nan with specific value
df.fillna(value=5)

# Create Boolean mask
pd.isna(df)
```

#### Categorical Data

```
df["biotype"] = df["raw_biotype"].astype("category")
df["biotype"].cat.categories = "protein_coding", "rRNA", "lincRNA"]


# Show distinct categories are present in dataset
df["biotype"].unique()

# Number of distinct categories 
df["biotype"].nunique()
```

#### Grouping

```
df.groupby('A').sum()

df.groupby(['A','C']).count().reset

```


#### String manipulation

In [ ]:
sample_names = {'samples' : ['mm_Chd7WTatac_R1','mm_Chd7WTatac_R2','mm_Chd7WTatac_R3','mm_Chd7KOatac_R1','mm_Chd7KOatac_R2','mm_Chd7KOatac_R3'],
                'file_type' : ['fastq.gz','fastq.gz','fastq.gz','fastq.gz','fastq.gz','fastq.gz']}
df = pd.DataFrame(sample_names)
df

In [ ]:
df['samples'].str.split('_')

In [ ]:
df['samples'].str.split('_',expand=True)

In [ ]:
df['replicate'] = df['samples'].str.split('_').str[-1]
df

#### Add column and set a value depending on another column

In [ ]:
df['samples'].str.contains('WT')

In [ ]:
df['condition'] = np.where(df['samples'].str.contains('WT'), 'WT', 'KO')
df

#### Combining Datasets


See documentation here: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

```
# Concatenate rows
pd.concat([df[:3], df[3:7], df[7:]])​

# Merge (inner by default)
result = pd.merge(df1, df2, on='key')
result = pd.merge(df1, df2, on='key', how='left')

# Join on index
result = df1.join(df2, how='outer')

# Join on key
result = df1.join(df2, on='key')
```

### Exercise 2

1) read in ensembl gtf files to create `gtf`

In [96]:
gtf = pd.read_csv("/ifs/obds-training/jan21/exercises/pandas/Mus_musculus.GRCm38.102.chr.gtf.gz", sep = '\t', header = None, comment = "#")


/ifs/obds-training/jan21/paulm/conda/obds_conda/envs/obds_py3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


2) Assign appropriate column names https://www.ensembl.org/info/website/upload/gff.html

In [97]:
gtf.columns = ['seqname', 'source', 'feature', 'start', 'end', 'score', 'strand', 'frame', 'attribute']
gtf.head()

seqname   source     feature    start      end score strand frame  \
0       1   havana        gene  3073253  3074322     .      +     .   
1       1   havana  transcript  3073253  3074322     .      +     .   
2       1   havana        exon  3073253  3074322     .      +     .   
3       1  ensembl        gene  3102016  3102125     .      +     .   
4       1  ensembl  transcript  3102016  3102125     .      +     .   

                                           attribute  
0  gene_id "ENSMUSG00000102693"; gene_version "1"...  
1  gene_id "ENSMUSG00000102693"; gene_version "1"...  
2  gene_id "ENSMUSG00000102693"; gene_version "1"...  
3  gene_id "ENSMUSG00000064842"; gene_version "1"...  
4  gene_id "ENSMUSG00000064842"; gene_version "1"...

3) Find the unique values for 'source' column

In [98]:
gtf['source'].unique()

array(['havana', 'ensembl', 'ensembl_havana', 'mirbase', 'insdc'],
      dtype=object)

4) Subset all values from 'ensembl_havana' and assign to new df called 'ens_df'

In [99]:
ens_df = gtf[gtf['source'] == 'ensembl_havana']
ens_df

seqname          source          feature     start       end score  \
6             1  ensembl_havana             gene   3205901   3671498     .   
13            1  ensembl_havana       transcript   3214482   3671498     .   
14            1  ensembl_havana             exon   3670552   3671498     .   
15            1  ensembl_havana              CDS   3670552   3671348     .   
16            1  ensembl_havana      start_codon   3671346   3671348     .   
...         ...             ...              ...       ...       ...   ...   
1868399      19  ensembl_havana      start_codon  61175993  61175995     .   
1868400      19  ensembl_havana       stop_codon  61175459  61175461     .   
1868401      19  ensembl_havana   five_prime_utr  61175996  61176309     .   
1868402      19  ensembl_havana  three_prime_utr  61174686  61175458     .   
1868407      19  ensembl_havana             gene  61223957  61228429     .   

        strand frame                                          attribute  
6            -     .  gene_id "ENSMUSG00000051951"; gene_version "5"...  
13           -     .  gene_id "ENSMUSG00000051951"; gene_version "5"...  
14           -     .  gene_id "ENSMUSG00000051951"; gene_version "5"...  
15           -     0  gene_id "ENSMUSG00000051951"; gene_version "5"...  
16           -     0  gene_id "ENSMUSG00000051951"; gene_version "5"...  
...        ...   ...                                                ...  
1868399      -     0  gene_id "ENSMUSG00000094649"; gene_version "1"...  
1868400      -     0  gene_id "ENSMUSG00000094649"; gene_version "1"...  
1868401      -     .  gene_id "ENSMUSG00000094649"; gene_version "1"...  
1868402      -     .  gene_id "ENSMUSG00000094649"; gene_version "1"...  
1868407      -     .  gene_id "ENSMUSG00000059326"; gene_version "7"...  

[558494 rows x 9 columns]

5) What is the size of ens_df?

In [102]:
ens_df.shape


(558494, 9)

6) What is the size of ens_df?

In [103]:
ens_df.shape

(558494, 9)

7) Group ens_df by 'feature' column & apply the 'count' function to get the number of rows in each feature

In [104]:
display(ens_df.groupby('feature').sum())
display(ens_df.groupby('feature').count())


start             end
feature                                        
CDS              15498367263615  15498401175865
Selenocysteine       1711915680      1711915726
exon             16527565840806  16527631853102
five_prime_utr    2280181473232   2280185942977
gene              1681144030164   1682202771711
start_codon       1611251981576   1611252024044
stop_codon        1596835675694   1596835717827
three_prime_utr   1648153114159   1648179394081
transcript        1687760689816   1688743752355

seqname  source   start     end   score  strand   frame  \
feature                                                                    
CDS               203373  203373  203373  203373  203373  203373  203373   
Selenocysteine        23      23      23      23      23      23      23   
exon              216470  216470  216470  216470  216470  216470  216470   
five_prime_utr     29833   29833   29833   29833   29833   29833   29833   
gene               22436   22436   22436   22436   22436   22436   22436   
start_codon        21291   21291   21291   21291   21291   21291   21291   
stop_codon         21101   21101   21101   21101   21101   21101   21101   
three_prime_utr    21645   21645   21645   21645   21645   21645   21645   
transcript         22322   22322   22322   22322   22322   22322   22322   

                 attribute  
feature                     
CDS                 203373  
Selenocysteine          23  
exon                216470  
five_prime_utr       29833  
gene                 22436  
start_codon          21291  
stop_codon           21101  
three_prime_utr      21645  
transcript           22322

8) Create a new df called 'genes' by subsetting all rows with 'gene' as a feature

In [105]:
genes_gtf = ens_df[ens_df['feature'] == 'gene'].copy()
display(genes_gtf)

seqname          source feature     start       end score strand  \
6             1  ensembl_havana    gene   3205901   3671498     .      -   
70            1  ensembl_havana    gene   3999557   4409241     .      -   
160           1  ensembl_havana    gene   4490931   4497354     .      -   
283           1  ensembl_havana    gene   4773206   4785739     .      -   
354           1  ensembl_havana    gene   4807788   4848410     .      +   
...         ...             ...     ...       ...       ...   ...    ...   
1868189      19  ensembl_havana    gene  60864051  60874556     .      -   
1868209      19  ensembl_havana    gene  60889749  61095968     .      +   
1868272      19  ensembl_havana    gene  61053840  61140840     .      -   
1868395      19  ensembl_havana    gene  61174686  61176309     .      -   
1868407      19  ensembl_havana    gene  61223957  61228429     .      -   

        frame                                          attribute  
6           .  gene_id "ENSMUSG00000051951"; gene_version "5"...  
70          .  gene_id "ENSMUSG00000025900"; gene_version "13...  
160         .  gene_id "ENSMUSG00000025902"; gene_version "13...  
283         .  gene_id "ENSMUSG00000033845"; gene_version "13...  
354         .  gene_id "ENSMUSG00000025903"; gene_version "14...  
...       ...                                                ...  
1868189     .  gene_id "ENSMUSG00000024997"; gene_version "7"...  
1868209     .  gene_id "ENSMUSG00000003228"; gene_version "9"...  
1868272     .  gene_id "ENSMUSG00000074733"; gene_version "14...  
1868395     .  gene_id "ENSMUSG00000094649"; gene_version "1"...  
1868407     .  gene_id "ENSMUSG00000059326"; gene_version "7"...  

[22436 rows x 9 columns]

9) Create a new column called 'gene_length' and calculate the length of each gene

In [106]:
genes_gtf["gene_length"] = genes_gtf["end"] - genes_gtf["start"]
genes_gtf

seqname          source feature     start       end score strand  \
6             1  ensembl_havana    gene   3205901   3671498     .      -   
70            1  ensembl_havana    gene   3999557   4409241     .      -   
160           1  ensembl_havana    gene   4490931   4497354     .      -   
283           1  ensembl_havana    gene   4773206   4785739     .      -   
354           1  ensembl_havana    gene   4807788   4848410     .      +   
...         ...             ...     ...       ...       ...   ...    ...   
1868189      19  ensembl_havana    gene  60864051  60874556     .      -   
1868209      19  ensembl_havana    gene  60889749  61095968     .      +   
1868272      19  ensembl_havana    gene  61053840  61140840     .      -   
1868395      19  ensembl_havana    gene  61174686  61176309     .      -   
1868407      19  ensembl_havana    gene  61223957  61228429     .      -   

        frame                                          attribute  gene_length  
6           .  gene_id "ENSMUSG00000051951"; gene_version "5"...       465597  
70          .  gene_id "ENSMUSG00000025900"; gene_version "13...       409684  
160         .  gene_id "ENSMUSG00000025902"; gene_version "13...         6423  
283         .  gene_id "ENSMUSG00000033845"; gene_version "13...        12533  
354         .  gene_id "ENSMUSG00000025903"; gene_version "14...        40622  
...       ...                                                ...          ...  
1868189     .  gene_id "ENSMUSG00000024997"; gene_version "7"...        10505  
1868209     .  gene_id "ENSMUSG00000003228"; gene_version "9"...       206219  
1868272     .  gene_id "ENSMUSG00000074733"; gene_version "14...        87000  
1868395     .  gene_id "ENSMUSG00000094649"; gene_version "1"...         1623  
1868407     .  gene_id "ENSMUSG00000059326"; gene_version "7"...         4472  

[22436 rows x 10 columns]

10) Calculate the mean and median of gene lengths

In [107]:
display(genes_gtf.describe())
display(np.median(genes_gtf['gene_length']))
display(genes_gtf['gene_length'].mean())

start           end   gene_length
count  2.243600e+04  2.243600e+04  2.243600e+04
mean   7.493065e+07  7.497784e+07  4.718941e+04
std    4.429087e+07  4.428967e+07  1.095276e+05
min    7.251280e+05  7.974090e+05  9.000000e+00
25%    3.671332e+07  3.674402e+07  5.905750e+03
50%    7.336766e+07  7.340731e+07  1.630850e+04
75%    1.080928e+08  1.081357e+08  4.379100e+04
max    1.951368e+08  1.951767e+08  2.960899e+06

16308.5

47189.4075147085

11) Find the top 10 longest genes

In [108]:
sorted_genes_by_length = genes_gtf.sort_values(by='gene_length', ascending = False).head(10)


12) Find the lowest 20 shortest genes

In [109]:
sorted_genes_by_length = genes_gtf.sort_values(by='gene_length', ascending = True).head(20)
display(sorted_genes_by_length)


seqname          source feature      start        end score strand  \
1516168      12  ensembl_havana    gene  113464761  113464770     .      -   
1516217      12  ensembl_havana    gene  113526800  113526809     .      -   
1516144      12  ensembl_havana    gene  113454942  113454951     .      -   
1516180      12  ensembl_havana    gene  113469426  113469435     .      -   
1516156      12  ensembl_havana    gene  113460101  113460110     .      -   
1119803      14  ensembl_havana    gene   54113468   54113478     .      +   
1516126      12  ensembl_havana    gene  113430528  113430538     .      -   
671211        6  ensembl_havana    gene   41533201   41533212     .      +   
1516134      12  ensembl_havana    gene  113449588  113449599     .      -   
671266        6  ensembl_havana    gene   41542163   41542176     .      +   
1516130      12  ensembl_havana    gene  113448214  113448229     .      -   
1119812      14  ensembl_havana    gene   54122226   54122241     .      +   
1516213      12  ensembl_havana    gene  113525313  113525329     .      -   
1516194      12  ensembl_havana    gene  113475400  113475416     .      -   
1516140      12  ensembl_havana    gene  113450851  113450867     .      -   
1516184      12  ensembl_havana    gene  113470694  113470710     .      -   
1516160      12  ensembl_havana    gene  113461369  113461385     .      -   
1516148      12  ensembl_havana    gene  113456720  113456736     .      -   
1516172      12  ensembl_havana    gene  113466027  113466043     .      -   
1516220      12  ensembl_havana    gene  113528032  113528054     .      -   

        frame                                          attribute  gene_length  
1516168     .  gene_id "ENSMUSG00000093876"; gene_version "1"...            9  
1516217     .  gene_id "ENSMUSG00000095549"; gene_version "1"...            9  
1516144     .  gene_id "ENSMUSG00000094957"; gene_version "1"...            9  
1516180     .  gene_id "ENSMUSG00000096396"; gene_version "1"...            9  
1516156     .  gene_id "ENSMUSG00000096884"; gene_version "1"...            9  
1119803     .  gene_id "ENSMUSG00000096749"; gene_version "2"...           10  
1516126     .  gene_id "ENSMUSG00000094028"; gene_version "1"...           10  
671211      .  gene_id "ENSMUSG00000095668"; gene_version "1"...           11  
1516134     .  gene_id "ENSMUSG00000096420"; gene_version "2"...           11  
671266      .  gene_id "ENSMUSG00000094569"; gene_version "1"...           13  
1516130     .  gene_id "ENSMUSG00000094552"; gene_version "1"...           15  
1119812     .  gene_id "ENSMUSG00000096176"; gene_version "1"...           15  
1516213     .  gene_id "ENSMUSG00000093818"; gene_version "1"...           16  
1516194     .  gene_id "ENSMUSG00000096568"; gene_version "1"...           16  
1516140     .  gene_id "ENSMUSG00000095656"; gene_version "1"...           16  
1516184     .  gene_id "ENSMUSG00000095444"; gene_version "1"...           16  
1516160     .  gene_id "ENSMUSG00000096250"; gene_version "1"...           16  
1516148     .  gene_id "ENSMUSG00000094057"; gene_version "1"...           16  
1516172     .  gene_id "ENSMUSG00000095897"; gene_version "1"...           16  
1516220     .  gene_id "ENSMUSG00000076632"; gene_version "1"...           22

13) Split attributes column on ';' and create new dataframe, merge this onto the ens_gtf dataframe using pandas merge ​

In [112]:
attributes = genes_gtf['attribute'].str.split(';', expand = True)
attributes
genes_full_attributes = pd.concat([genes_gtf, attributes], axis = 1)
display(genes_full_attributes)

seqname          source feature     start       end score strand  \
6             1  ensembl_havana    gene   3205901   3671498     .      -   
70            1  ensembl_havana    gene   3999557   4409241     .      -   
160           1  ensembl_havana    gene   4490931   4497354     .      -   
283           1  ensembl_havana    gene   4773206   4785739     .      -   
354           1  ensembl_havana    gene   4807788   4848410     .      +   
...         ...             ...     ...       ...       ...   ...    ...   
1868189      19  ensembl_havana    gene  60864051  60874556     .      -   
1868209      19  ensembl_havana    gene  60889749  61095968     .      +   
1868272      19  ensembl_havana    gene  61053840  61140840     .      -   
1868395      19  ensembl_havana    gene  61174686  61176309     .      -   
1868407      19  ensembl_havana    gene  61223957  61228429     .      -   

        frame                                          attribute  gene_length  \
6           .  gene_id "ENSMUSG00000051951"; gene_version "5"...       465597   
70          .  gene_id "ENSMUSG00000025900"; gene_version "13...       409684   
160         .  gene_id "ENSMUSG00000025902"; gene_version "13...         6423   
283         .  gene_id "ENSMUSG00000033845"; gene_version "13...        12533   
354         .  gene_id "ENSMUSG00000025903"; gene_version "14...        40622   
...       ...                                                ...          ...   
1868189     .  gene_id "ENSMUSG00000024997"; gene_version "7"...        10505   
1868209     .  gene_id "ENSMUSG00000003228"; gene_version "9"...       206219   
1868272     .  gene_id "ENSMUSG00000074733"; gene_version "14...        87000   
1868395     .  gene_id "ENSMUSG00000094649"; gene_version "1"...         1623   
1868407     .  gene_id "ENSMUSG00000059326"; gene_version "7"...         4472   

                                    0                   1  \
6        gene_id "ENSMUSG00000051951"    gene_version "5"   
70       gene_id "ENSMUSG00000025900"   gene_version "13"   
160      gene_id "ENSMUSG00000025902"   gene_version "13"   
283      gene_id "ENSMUSG00000033845"   gene_version "13"   
354      gene_id "ENSMUSG00000025903"   gene_version "14"   
...                               ...                 ...   
1868189  gene_id "ENSMUSG00000024997"    gene_version "7"   
1868209  gene_id "ENSMUSG00000003228"    gene_version "9"   
1868272  gene_id "ENSMUSG00000074733"   gene_version "14"   
1868395  gene_id "ENSMUSG00000094649"    gene_version "1"   
1868407  gene_id "ENSMUSG00000059326"    gene_version "7"   

                           2                              3  \
6           gene_name "Xkr4"   gene_source "ensembl_havana"   
70           gene_name "Rp1"   gene_source "ensembl_havana"   
160        gene_name "Sox17"   gene_source "ensembl_havana"   
283       gene_name "Mrpl15"   gene_source "ensembl_havana"   
354       gene_name "Lypla1"   gene_source "ensembl_havana"   
...                      ...                            ...   
1868189    gene_name "Prdx3"   gene_source "ensembl_havana"   
1868209     gene_name "Grk5"   gene_source "ensembl_havana"   
1868272   gene_name "Zfp950"   gene_source "ensembl_havana"   
1868395   gene_name "Gm7102"   gene_source "ensembl_havana"   
1868407   gene_name "Csf2ra"   gene_source "ensembl_havana"   

                                      4                                  5  \
6         gene_biotype "protein_coding"   havana_gene "OTTMUSG00000026353"   
70        gene_biotype "protein_coding"   havana_gene "OTTMUSG00000049985"   
160       gene_biotype "protein_coding"   havana_gene "OTTMUSG00000050014"   
283       gene_biotype "protein_coding"   havana_gene "OTTMUSG00000029329"   
354       gene_biotype "protein_coding"   havana_gene "OTTMUSG00000021562"   
...                                 ...                                ...   
1868189   gene_biotype "protein_coding"   havana_gene "OTTMUSG00000021212"   
1868209 

Extra: 
    Count the number of genes per chromosome, and add the number of genes per chomosome onto the idxdf from earlier ​

In [ ]:


display(ens_df.groupby('feature').count())